import time
import json
from lursoft_lv import *

if __name__ == '__main__':
    start_time = time.time()

    a = Handler()
    # final_data = a.Execute('aHR0cHM6Ly9jb21wYW55Lmx1cnNvZnQubHYvZW4vY2l0YWRlbGUtYmFua2EvNDAxMDMzMDM1NTk=',
    #                        'graph:shareholders', '', '')
    final_data = a.Execute('Akciju sabiedrība "Citadele banka','','','')
    # final_data = a.Execute('eyckaWQnOiAnMycsICdJbnRlcm5hdGlvblNlY0lOJzogJ05HQUNDRVNTMDAwNScsICdTeW1ib2wnOiAnQUNDRVNTJywgJ1ByZXZDbG9zZSc6IDEwLjQsICdPcGVuUHJpY2UnOiAxMC40LCAnRGF5c0hpZ2gnOiAxMC40LCAnRGF5c0xvdyc6IDEwLjMsICdWb2x1bWUnOiAyNjc3Njk3Mi4wLCAnVmFsdWUnOiAyNzc5NzQwOTQuMzUsICdNYXJrZXRDYXAnOiAzNjYxMTU4MjM5MDYuNiwgJ1NoYXJlc091dHN0YW5kaW5nJzogMzU1NDUyMjU2MjIuMCwgJ0RpdmlkZW5kJzogTm9uZSwgJ1lpZWxkJzogTm9uZSwgJ1NlY3Rvcic6ICdGSU5BTkNJQUwgU0VSVklDRVMnLCAnU3ViU2VjdG9yJzogJ0JhbmtpbmcnLCAnQ29tcGFueU5hbWUnOiAnQUNDRVNTIEJBTksgUExDLicsICdNYXJrZXRDbGFzc2lmaWNhdGlvbic6ICdQcmVtaXVtIEJvYXJkJywgJ0RhdGVMaXN0ZWQnOiBOb25lLCAnRGF0ZU9mSW5jb3Jwb3JhdGlvbic6ICcxOTg5LTAyLTA4VDAwOjAwOjAwJywgJ1dlYnNpdGUnOiAnd3d3LmFjY2Vzc2JhbmtwbGMuY29tJywgJ0xvZ291cmwnOiAnd3d3LmFjY2Vzc2JhbmtwbGMuY29tJywgJ1N0b2NrUHJpY2VQZXJjQ2hhbmdlJzogLTAuOTYsICdTdG9ja1ByaWNlQ2hhbmdlJzogLTAuMSwgJ1N0b2NrUHJpY2VDdXInOiAxMC4zLCAnQ29tcGFueVByb2ZpbGVTdW1tYXJ5JzogTm9uZSwgJ05hdHVyZW9mQnVzaW5lc3MnOiAnQ29tbWVyY2lhbCBCYW5raW5nJywgJ0NvbXBhbnlBZGRyZXNzJzogJ0FjY2VzcyBUb3dlciBQbG90IDE0LzE1LCBQcmluY2UgQWxhYmEgT25pcnUgU3RyZWV0LCBPbmlydSBFc3RhdGUsIFZpY3RvcmlhIElzbGFuZCwgTGFnb3MnLCAnVGVsZXBob25lJzogJzIzNDEyODA1NjI4JywgJ0ZheCc6ICdBQ0NFU1MgQkFOSyBQTEMgMDI5MjAwMzI4QzNOOVlJMkQ2NjAnLCAnRW1haWwnOiAnaW5mb0BhY2Nlc3NiYW5rcGxjLmNvbScsICdDb21wYW55U2VjcmV0YXJ5JzogJ01yLiBTdW5kYXkgRWt3b2NoaScsICdBdWRpdG9yJzogJ1ByaWNld2F0ZXJob3VzZUNvb3BlcnMnLCAnUmVnaXN0cmFycyc6IE5vbmUsICdCb2FyZE9mRGlyZWN0b3JzJzogJ0Fqb3JpdHNlZGVyZSAgQXdvc2lrYSwgRHIuIEdyZWdvcnkgSm9ib21lICwgRHIuIE9rZXkgTnd1a2UgLCBIYXNzYW4gIFVzbWFuLCBNciBQYXVsIFVzb3JvOyBTQU4gLCBNci4gQWRlIEJham9tbyAsIE1yLiBBZGVuaXlpIEFkZWtveWEgICwgTXIuIEhlcmJlcnQgV2lnd2UgLCBNci4gSWJvcm9tYSBBa3BhbmEgICwgTXIuIFJvb3NldmVsdCBPZ2Jvbm5hICwgTXIuIFZpY3RvciBFdHVva3d1ICwgTXJzLiBBbnRob25pYSBLZW1pIE9ndW5tZWZ1biAsIE1ycy4gQ2hpem9tYSBPa29saSAsIE1ycy4gSWZleWlud2EgT3NpbWUgICwgTXMuIEhhZGl6YSBBbWJ1cnNhICwgT2x1c2V5aSAgS3VtYXBheWksIE9tb3NhbGV3YSBGYWpvYmknLCAnSUQnOiA1LCAnSElHSDUyV0tfUFJJQ0UnOiAxMC42LCAnSElHSDUyV0tfREFURVRJTUUnOiAnMjAyMi0wMi0xMVQwMDowMDowMCcsICdMT1c1MldLX1BSSUNFJzogNy4wNSwgJ0xPVzUyV0tfREFURVRJTUUnOiAnMjAyMS0wNC0yN1QwMDowMDowMCcsICdTeW1ib2wyJzogJ0FDQ0VTUyAgW0NHK10nLCAnTFNfU1REJzogJyxbQ0crXScsICdPRkZJQ0lBTF9PUEVOJzogTm9uZSwgJ09GRklDSUFMX0NMT1NFJzogMTAuMywgJ0xhc3RVcGxvYWRJbmZvJzogTm9uZSwgJ1F1YXRlcklEJzogTm9uZSwgJ1F1YXRlclllYXInOiBOb25lLCAnVG90YWxBc3NldHNVbmRlck1hbmFnZW1lbnQnOiBOb25lLCAnaW1nUGF0aCc6IE5vbmUsICdBZGRyZXNzJzogTm9uZSwgJ0NhYmxlJzogTm9uZSwgJ1BBZGRyZXNzJzogTm9uZSwgJ1RlbGV4JzogTm9uZX0=',
    #                        'overview','','')
    print(json.dumps(final_data, indent=4))

    elapsed_time = time.time() - start_time
    print('\nTask completed - Elapsed time: ' + str(round(elapsed_time, 2)) + ' seconds')
